apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: observabilidade
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - name: prometheus
      port: 9090
      targetPort: 9090
