apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observabilidade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.external-url=/prometheus
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 48m
              memory: 54Mi
            limits:
              cpu: 100m
              memory: 128Mi
