apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: observabilidade
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
