apiVersion: apps/v1
kind: Deployment
metadata:
  name: banco
  namespace: db-namespace
  labels:
    app: banco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banco
  template:
    metadata:
      labels:
        app: banco
    spec:
      containers:
      - name: banco
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1010"
        - name: POSTGRES_DB
          value: "greenlearning"
        ports:
        - containerPort: 5432
