- name: Configurar VM e subir Grafana e Prometheus
  hosts: all
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Criar diretório /home/ubuntu/app
      file:
        path: /home/ubuntu/app
        state: directory
        mode: '0755'

    - name: Copiar prometheus.yml
      copy:
        src: ../prometheus.yml
        dest: /home/ubuntu/app/prometheus.yml

    - name: Subir containers com Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/app