- name: Configurar Prometheus, Grafana e Banco de Dados no Kubernetes
  hosts: localhost  # Rodar localmente, já que o acesso ao cluster Kubernetes será configurado
  tasks:
    - name: Aplicar manifestos do Prometheus
      k8s:
        state: present
        src: ./prometheus-deployment.yml  # Caminho para o manifesto do Prometheus
        kubeconfig: "/home/runner/kubeconfig"  # Caminho para o kubeconfig gerado pelo Terraform
    
    - name: Aplicar manifestos do Grafana
      k8s:
        state: present
        src: ./grafana-deployment.yml  # Caminho para o manifesto do Grafana
        kubeconfig: "/home/runner/kubeconfig"
    
    - name: Aplicar manifestos do Banco de Dados
      k8s:
        state: present
        src: ./database-deployment.yml  # Caminho para o manifesto do Banco de Dados
        kubeconfig: "/home/runner/kubeconfig"