- name: Configurar VM e subir Grafana e Prometheus
  hosts: all
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: yes

    - name: Instalar Docker e Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Clonar repositório do projeto
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dest }}"
        version: "{{ repo_branch }}"
        force: yes

    - name: Subir containers com Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/ubuntu/app
