
name: 'infra com terraform'

on:
  push:
    branches:
      - developer6
  workflow_dispatch:

jobs:
  infra:
    name: 'infra'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4


      - name: Autenticar no Google Cloud via Chave de Serviço
        id: auth
        uses: google-github-actions/auth@v2
        with:

          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Verificar Autenticação GCP
        run: |
          echo "--- Verificando identidade autenticada ---"
          gcloud auth list
          echo "--- Verificando projeto configurado ---"
          gcloud config list

      - name: Setup do Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Executar Terraform para Staging
        env:
          TF_VAR_grafana_admin_password: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        run: |
          cd terraform
          terraform init -backend-config=homol.tfbackend
          terraform workspace select homol || terraform workspace new homol
          terraform plan -var-file="homol.tfvars" -out=tfplan
          terraform apply -auto-approve tfplan